### PR TITLE
Fix blocking io

### PR DESCRIPTION
**Pull request by sergiobd007**
My code was blocking the main thread and arduino doesn't block on input read. This should fix it.

### CODE REVIEW

**Comment by ChrisMicro** [comment]
Hi Sergio,
just tried the make file in ..examples/input

There are some errors:

build//home/christoph/Entwicklung/170721_ArduinoOnPc/sergiobd007/ArduinoOnPc/src/cores/arduino/SerialConsole.o: In Funktion `std::thread::thread<void (&)()>(void (&)())':
SerialConsole.cpp:(.text._ZNSt6threadC2IRFvvEJEEEOT_DpOT0_[_ZNSt6threadC5IRFvvEJEEEOT_DpOT0_]+0x7d): Nicht definierter Verweis auf `pthread_create'
/usr/bin/ld generated: Nicht definierter Verweis auf `pthread_create'
collect2: error: ld returned 1 exit status
../../makeNativeArduino.mk:56: die Regel für Ziel „main“ scheiterte
make: *** [main] Fehler 1

The problem could probably be in the make file:
https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux

**Comment by sergiobd007** [comment]
I must have a weird setup because it was compiling fine in my computer. Can you try it now?

**Comment by ChrisMicro** [comment]
Hi Sergio,
thank you for the changes. It looks like it remains the same:

sergiobd007/ArduinoOnPc/e
xamples/Blink$ make   
build//home/christoph/Entwicklung/170721_ArduinoOnPc/sergiobd007/ArduinoOnPc/src/cores/arduino/SerialConsole.o: In function `std::thread::thread<void (&)()>(void (&)())':
SerialConsole.cpp:(.text._ZNSt6threadC2IRFvvEJEEEOT_DpOT0_[_ZNSt6threadC5IRFvvEJEEEOT_DpOT0_]+0x7d): undefined reference to `pthread_create'
/usr/bin/ld generated: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
../../makeNativeArduino.mk:66: recipe for target 'Blink' failed
make: *** [Blink] Error 1

I tried also to compile the old version on another computer. There were some warnings about missing
sdl2-config which are remainders of benpiccos changes to SDL2.
Because SDL2 is not used in the current version, the  parts in make file should be probably removed:

e.g. CXXFLAGS += -DFASTLED_SDL $(shell sdl2-config --cflags)

**Comment by sergiobd007** [comment]
I'm working on adding LED support to this project [on this branch](https://github.com/sergiobd007/ArduinoOnPc/tree/led_support), so that dependencies will be necessary. I don't know if you want to integrate that changes on this repo. Right now I can make both TFT and LED sketches using that repo.

And about the compilation problem I switched the flag to the correct place, but I don't think that's the problem. If you can't look at the problem yourself, I will try to test it on another machine to try to reproduce it.

**Comment by ChrisMicro** [comment]
> I'm working on adding LED support to this project [on this branch](https://github.com/sergiobd007/ArduinoOnPc/tree/led_support), so that dependencies will be necessary. I don't know if you want to integrate that changes on this repo. Right now I can make both TFT and LED sketches using that repo.

Yes, it would be could to have your changes in the main branch. 
I wondered if both principles X11 and SDL2 can coexist and work at the same time. Probably it would be good to have only SDL2. Possibly it would work on other OS like MAC or Win too. But this would require to adapt the TFT-driver to SDL2.
The idea of benpicco to include the libraries as subproject is very convenient. But I'm not sure if the SDL requests should be in the library file. In Fastled there is also a keyboard request to decrease or increase the brightness. In my opinion this should be somewhere outside because it might be conflict with your Serial.read().

At the moment with your last commit "Blink" is compiling. But the TFT things which require X11 do not compile any more. I will see later on how this could be solved.

I appriciate your work and I'm curious what you are doing with the project.

**Comment by sergiobd007** [comment]
> I wondered if both principles X11 and SDL2 can coexist and work at the same time. Probably it would be good to have only SDL2. Possibly it would work on other OS like MAC or Win too. But this would require to adapt the TFT-driver to SDL2.

This is something I wouldn't know where to begin with. I dont have any experience with X11 nor SDL2. It doesn't seem like it should be very difficult though, as it's only detecting touches and drawing pixels, but I don't know how SDL2 works.

> The idea of benpicco to include the libraries as subproject is very convenient. But I'm not sure if the SDL requests should be in the library file. In Fastled there is also a keyboard request to decrease or increase the brightness. In my opinion this should be somewhere outside because it might be conflict with your Serial.read().

Perhaps I'm missing something but I think it shouldn't conflict as I'm reading from terminal and that is a separate window. On the one hand it's cool to have it on the library as this way it's trivial to keep it updated. The problem is that it might be more difficult to integrate it for another use case (let's say for example in a complex GUI).

>At the moment with your last commit "Blink" is compiling. But the TFT things which require X11 do not compile any more. I will see later on how this could be solved.

I think it was a problem with the submodule naming. It's working now for me.

>I appriciate your work and I'm curious what you are doing with the project.

If you are referring to what I'm using it for I'm doing a [word clock](https://duckduckgo.com/?q=word+clock&t=h_&iar=images&iax=images&ia=images). I wanted to be able to do some LED animations without having to set up the hardware beforehand and I stumbled upon this project.

If you mean what I'd like to do with the project I'd like to do an open source _simulator_ (kind of) with a minimal GUI, but I don't know if I will get to that point.

**Comment by ChrisMicro** [comment]
> If you mean what I'd like to do with the project I'd like to do an open source _simulator_ (kind of) with a minimal GUI, but I don't know if I will get to that point.

That sounds interesting. What shall the simulator exactly do?
I was thinking of making just a little input-GUI ( probably with buttons as pin control. sliders for ADC control) and using linux pipes to pipe it into the main Arduino program.

Probably somthing like
arduGui | arduprogram | pinVisualizer

But I'm still thinking if this is the right way ...

**Comment by ChrisMicro** [comment]
Hi Sergio,
I selectively added your none blocking changes because I couldn't manage to get the new make file running.
Now it works on my system and I hope on yours too.

**Comment by sergiobd007** [comment]
>Probably somthing like
`arduGui | arduprogram | pinVisualizer`

I was thinking about integrating the comunication in the code itself. We would launch a GUI in the main.cpp that executes the program and the code of the program interacts with this interface, for example writing the Serial output in a part of the window, having a place for the leds in case it's needed, etc.

>I selectively added your none blocking changes because I couldn't manage to get the new make file running.
 Now it works on my system and I hope on yours too.

Yes it works

**Comment by sergiobd007** [comment]
I removed the commits you alredy manually merged, you should be able to merge this branch to add the example.

**Pull request merged**
